version: '3.0'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: Contactabilidad_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: unab1234

  redis:
    image: "redis:alpine"

  web:
    build: .
    image: contactabilidad
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - "8080:8080"
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      NAME: Contactabilidad_db
      USER: root
      PASSWORD: unab1234
      HOST: db
      REDIS_URL: redis

  migrate:
    image: contactabilidad
    command: python manage.py migrate
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    environment:
      NAME: Contactabilidad_db
      USER: root
      PASSWORD: unab1234
      HOST: db

  #redis:
  #  container_name: redis
  #  image: redis:2.8
  #  command: ["redis-server", "--appendonly", "yes"]
  #  hostname: redis
  #  expose:
  #    - 6379
  #  networks:
  #    - redis-net
  #  volumes:
  #    - redis-data:/data
  #  ports:
  #      - "6379:6379"
