version: '2.1'

services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: contactabilidad_db
    healthcheck:
      test: mysql -h localhost -u root -p1234 -Bse "show databases;"
      interval: 5s

  web:
    build: .
    image: contactabilidad
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      NAME: contactabilidad_db
      USER: root
      PASSWORD: 1234
      HOST: db

  migrate:
    image: contactabilidad
    command: python  manage.py migrate
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy
    environment:
      NAME: contactabilidad_db
      USER: root
      PASSWORD: 1234
      HOST: db
